### ISSUE TITLE
Unable to find wpilib.shuffleboard in 2021 or 2022 libraries

### ISSUE THREAD

**Issue by aesatchien** [robotpy/robotpy-wpilib#705] opened 2022-02-28 19:32 UTC
https://github.com/robotpy/examples/tree/main/shuffleboard shows a 
`from wpilib.shuffleboard import Shuffleboard` call.   I know robotpy has changed a lot since 2018, but I can't find it where I would think to look for it based on the organization of the Java API.  I don't see any likely candidates when I do a `dir(wpilib)` after importing it.  Is it still supported?

**Comment by virtuald** [comment] 2022-02-28 20:06
It is currently broken.

**Comment by aesatchien** [comment] 2022-02-28 20:26
Good to know.  Thanks!

**Comment by auscompgeek** [comment] 2022-02-28 21:24
Duplicate of #691

**Closed** 2022-02-28 21:24 UTC
