### ISSUE TITLE
Race condition in getStickButton

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#473] opened 2018-07-19 14:15 UTC
If a user calls `DriverStation.getStickButton` in `robotInit()` (for example, when initializing a `JoystickButton` command) , they'll get a warning that the button does not exist yet. This happens because the initial count of all buttons is zero, and the count doesn't get updated until the DS thread executes at least a single loop.

WPILib seems like it would have the same issue, except that presumably their thread gets executed in time and so the warning never occurs (or people just ignore it).

A workaround could be just to initialize the button count to the max number. Once the ds thread updates, once the user calls the thing again they'll get the warning if it's needed.

Reference: https://www.chiefdelphi.com/forums/showthread.php?threadid=166029

**Comment by Starlight220** [comment] 2020-04-19 11:58
@virtuald , there is no point in having 3 GitHub issues for the same thing. This seems to be an exact duplicate of #1198, so close one of them.

**Closed** 2023-11-13 02:59 UTC
Labels: bug
