### ISSUE TITLE
Client Connected with bad protocol revision

### ISSUE THREAD

**Issue by ariovistus** [robotpy/robotpy-wpilib#178] opened 2016-01-23 17:50 UTC
When trying to run last year's code on last year's robot with this year's robotpy and this year's driver station, I'm seeing 

Client Connected with bad protocol revision: 0x300

and that's coming from pynetworktables which does not appear to have a release for this year. Is that the case currently?

**Comment by PeterJohnson** [comment] 2016-01-23 18:28
Correct, pynetworktables does not yet support NetworkTables 3.0.  Dashboards (e.g. SmartDashboard) that use the ntcore library will automatically reconnect with the 2.0 protocol.  However, the LabView dashboard will not (this year's dashboard only supports the 3.0 protocol).

**Comment by virtuald** [comment] 2016-01-29 23:16
Duplicate of https://github.com/robotpy/pynetworktables/issues/21

**Closed by virtuald** 2016-01-29 23:16 UTC
